### ISSUE TITLE
orcid in citation file for all contributors

### ISSUE THREAD

**Issue by Shimwell** [fusion-energy/cad_to_h5m#43]
@LukeLabrie  and @AnderGray feel free to add your orcid to this file https://github.com/fusion-energy/cad_to_h5m/blob/develop/CITATION.cff which is used by github to help people cite the code

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

You can see how this appears on the right hand side if you view the development branch

**Comment by Shimwell** [comment]
Or just messag me your orcid to this issue and I can add it to the file

**Comment by AnderGray** [comment]
Thanks Jon,
Mine is: https://orcid.org/0000-0002-1585-0900
