### ISSUE TITLE
import cubit failed

### ISSUE THREAD

**Issue by fnovais11** [fusion-energy/cad_to_h5m#60]
Error when trying to run it

`ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
$ Cell 1 in <cell line: 7>()
      [4](vscode-notebook-cell:/home/felipe/Dropbox/UTK/MALDONADO/OPENMC/dagmc/dag.ipynb#ch0000000?line=3) import urllib.request
      [5](vscode-notebook-cell:/home/felipe/Dropbox/UTK/MALDONADO/OPENMC/dagmc/dag.ipynb#ch0000000?line=4) from cad_to_h5m import cad_to_h5m
----> [7](vscode-notebook-cell:/home/felipe/Dropbox/UTK/MALDONADO/OPENMC/dagmc/dag.ipynb#ch0000000?line=6) cad_to_h5m(
...
--> 111     raise ImportError(msg)
    113 cubit.init([])
    114 if not verbose:

ImportError: import cubit failed, cubit was not importable from the provided path /opt/Coreform-Cubit-2021.11/bin/`

> fnovais@necluster ~ $ ll /opt/Coreform-Cubit-2021.5/bin/plugins/
total 268
drwxrwxr-x 2 root     root   4096 Jul  2  2021 assetimporters
drwxrwxr-x 2 root     root   4096 Jul  2  2021 audio
drwxrwxr-x 2 root     root   4096 Jul  2  2021 canbus
drwxrwxr-x 2 root     root   4096 Jul  2  2021 egldeviceintegrations
drwxrwxr-x 2 root     root   4096 Jul  2  2021 gamepads
drwxrwxr-x 2 root     root   4096 Jul  2  2021 generic
drwxrwxr-x 2 root     root   4096 Jul  2  2021 geometryloaders
drwxrwxr-x 2 root     root   4096 Jul  2  2021 geoservices
drwxrwxr-x 2 root     root   4096 Jul  2  2021 iconengines
drwxrwxr-x 2 root     root   4096 Jul  2  2021 imageformats
-rwxr-xr-x 1 root     root 136720 May 28  2021 libmaterial_commands.so
lrwxrwxrwx 1 galloway  121     28 Jun 22  2021 libsvalinn_plugin.so -> svalinn/libsvalinn_plugin.so
drwxrwxr-x 2 root     root   4096 Jul  2  2021 mediaservice
drwxrwxr-x 2 root     root   4096 Jul  2  2021 platforminputcontexts
drwxrwxr-x 2 root     root   4096 Jul  2  2021 platforms
drwxrwxr-x 2 root     root   4096 Jul  2  2021 platformthemes
drwxrwxr-x 2 root     root   4096 Jul  2  2021 playlistformats
drwxrwxr-x 2 root     root   4096 Jul  2  2021 position
drwxrwxr-x 2 root     root   4096 Jul  2  2021 printsupport
drwxrwxr-x 2 root     root   4096 Jul  2  2021 qmltooling

**Comment by shimwell** [comment]
Thanks for rasing the issue.

From the error message I can see that the cad_to_h5m function is looking in the ```/opt/Coreform-Cubit-2021.11/bin/``` folder while the ```ll``` command you have shown is for the ```/opt/Coreform-Cubit-2021.5/bin/plugins/``` folder.

Perhaps the solution is to call ```cad_to_h5m``` with the ```cubit_path``` set to ```/opt/Coreform-Cubit-2021.5/bin/``` (which I think is the default)

**Comment by fnovais11** [comment]
Shimwell,

thank you for your reply.

The `cubit_path` parameter is set to `/opt/Coreform-Cubit-2021.5/bin/`. I only sent `ll /opt/Coreform-Cubit-2021.5/bin/plugins/` to demonstrate that cubit and the cubit plugin are installed. I have tried with versions 2021.5, 2021.11 and 2022, but it always gives me the same error.

**Comment by shimwell** [comment]
Thanks for the clarification, if you are free for a quick zoom call and screen share perhaps we can get this working together

**Comment by fnovais11** [comment]
Absolutely, if you are available 
https://zoom.us/j/5537365457?pwd=dzJGYU40Rkt3ZXNSd2JQRDVJa3pXUT09

**Comment by shimwell** [comment]
Thanks for the meet up just now @fnovais11, glad that we could get it working.

For anyone else reading this thread it looks like cubit is only importable in python 3.8

So the solution was to make a new python environment

``bash
conda create --name openmc-dev-3.8 python=3.8
```
