### ISSUE TITLE
Import Cubit Failed 

### ISSUE THREAD

**Issue by Sabyaro** [fusion-energy/cad_to_h5m#61]
I have installed cad_to_h5m, Coreform Cubit 2023.8 version and does the Svalinn plugin. But when I am going to run a code in the jupyter notebook given below it shows that import cubit is failed. 

from cad_to_h5m import cad_to_h5m

cad_to_h5m(
    files_with_tags=[{'cad_filename':'cylinder_cubit_1.stp', 'material_tag':'m1'}],
    h5m_filename='dagmc.h5m',
    cubit_path='/opt/Coreform-Cubit-2023.8/bin/'
)

The complete error message is given below: 

ImportError                               Traceback (most recent call last)
File ~/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/cad_to_h5m/core.py:104, in cad_to_h5m(files_with_tags, h5m_filename, cubit_path, cubit_filename, merge_tolerance, faceting_tolerance, make_watertight, imprint, geometry_details_filename, surface_reflectivity_name, exo_filename, implicit_complement_material_tag, verbose, autoheal)
    103 try:
--> 104     import cubit
    105 except ImportError:

File /opt/Coreform-Cubit-2021.5/bin/cubit.py:32
     31 else:
---> 32   from cubit3 import *

File /opt/Coreform-Cubit-2021.5/bin/cubit3.py:15
     14 else:
---> 15     import _cubit3
     17 try:

ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Cell In[8], line 3
      1 from cad_to_h5m import cad_to_h5m
----> 3 cad_to_h5m(
      4     files_with_tags=[{'cad_filename':'cylinder_cubit_1.stp', 'material_tag':'m1'}],
      5     h5m_filename='dagmc.h5m',
      6     cubit_path='/opt/Coreform-Cubit-2023.8/bin/'
      7 )

File ~/NuclearBoy/nuclear-boy/lib/python3.10/site-packages/cad_to_h5m/core.py:110, in cad_to_h5m(files_with_tags, h5m_filename, cubit_path, cubit_filename, merge_tolerance, faceting_tolerance, make_watertight, imprint, geometry_details_filename, surface_reflectivity_name, exo_filename, implicit_complement_material_tag, verbose, autoheal)
    105 except ImportError:
    106     msg = (
    107         "import cubit failed, cubit was not importable from the "
    108         f"provided path {cubit_path}"
    109     )
--> 110     raise ImportError(msg)
    112 cubit.init([])
    113 if not verbose:

ImportError: import cubit failed, cubit was not importable from the provided path /opt/Coreform-Cubit-2023.8/bin/

Can you advice something to solve this problem?

**Comment by shimwell** [comment]
Hi

I guess the first thing to try is to look in the ```/opt/Coreform-Cubit-2021.5/bin/``` folder and see if there are any .so files in there.

**Comment by Sabyaro** [comment]
Thank you. I have solved the problem
